# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czI94Lpos7QGwWVIqSLWE3UUQolRvQ25
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- 1. App Title & Description ---
st.set_page_config(page_title="Smart Irrigation System", page_icon="💧", layout="wide")

# --- Function to add Background Image & Custom CSS for Bold Text ---
def add_custom_style():
    st.markdown(
         f"""
         <style>
         /* 1. Background Image */
         .stApp {{
             background-image: url("https://github.com/malvani-surfer/Smart-Irrigation-App/blob/17f07327b59683c8bd1c907b84392fc59e16d6a9/China%20Photo.jpg?raw=true");
             background-attachment: fixed;
             background-size: cover;
         }}

         /* 2. White Overlay for Readability */
         .stApp::before {{
             content: "";
             position: absolute;
             top: 0;
             left: 0;
             width: 100%;
             height: 100%;
             background-color: rgba(255, 255, 255, 0.85);
             z-index: -1;
         }}

         /* 3. Make ALL Text Bolder and Darker */
         h1, h2, h3, h4, h5, h6, p, div, span, label {{
             font-weight: 700 !important;
             color: #111111 !important;
         }}

         /* Specific styling for Metrics to pop */
         div[data-testid="stMetricValue"] {{
             font-weight: 900 !important;
             color: #000000 !important;
         }}
         div[data-testid="stMetricLabel"] {{
             font-weight: bold !important;
             color: #333333 !important;
         }}
         </style>
         """,
         unsafe_allow_html=True
     )

add_custom_style()

st.title("💧 Smart Irrigation Scheduler")
st.markdown("### AI-Driven Precision Farming for Kamshet Region")

# --- 2. Sidebar: Inputs ---
st.sidebar.header("🚜 Farm Parameters")
crop_type = st.sidebar.selectbox("Select Crop Type", ["Rice", "Wheat", "Tomato", "Sugarcane"])
farm_area = st.sidebar.number_input("Farm Area (Hectares)", min_value=0.1, value=1.0)
pump_rate = st.sidebar.number_input("Pump Flow Rate (Liters/Hour)", value=2000)

st.sidebar.header("🌦️ Weather Conditions (Today)")
temp_max = st.sidebar.slider("Max Temp (°C)", 10.0, 45.0, 32.0)
humidity = st.sidebar.slider("Humidity (%)", 10, 100, 60)
wind_speed = st.sidebar.slider("Wind Speed (m/s)", 0.0, 15.0, 2.5)
radiation = st.sidebar.slider("Solar Radiation (MJ/m²)", 5.0, 30.0, 18.0)

# --- 3. Logic Layer (Backend) ---
def calculate_irrigation(et0, crop, area, rate):
    kc_map = {'Rice': 1.2, 'Wheat': 1.15, 'Tomato': 0.85, 'Sugarcane': 1.25}
    kc = kc_map.get(crop, 1.0)

    water_mm = et0 * kc
    water_liters = water_mm * area * 10000
    runtime_hours = water_liters / rate
    runtime_minutes = runtime_hours * 60

    return water_mm, water_liters, runtime_minutes

def predict_et0(t, h, w, r):
    return (0.025 * (t + 20) * (1 - h/100) * (0.5 + w/5)) + (r * 0.1)

# --- 4. Main Dashboard ---
if st.button("🚀 Calculate Irrigation Schedule"):

    # --- A. Prediction & Metrics ---
    predicted_et0 = predict_et0(temp_max, humidity, wind_speed, radiation)
    water_need_mm, water_vol, run_time = calculate_irrigation(predicted_et0, crop_type, farm_area, pump_rate)

    st.divider()

    col1, col2, col3 = st.columns(3)
    col1.metric("Predicted ET0", f"{predicted_et0:.2f} mm/day")
    col2.metric("Total Water Required", f"{water_vol:,.0f} Liters")
    col3.metric("Pump Runtime", f"{run_time:.0f} Minutes")

    if run_time > 60:
        st.warning(f"⚠️ **High Water Demand!** Run pump for **{int(run_time)} minutes** ({run_time/60:.1f} hours).")
    else:
        st.success(f"✅ **Optimal Condition.** Run pump for **{int(run_time)} minutes**.")

    st.divider()

    # --- B. Visual Analysis (Opaque Graphs) ---
    st.subheader("📊 Analytical Insights")

    chart_col1, chart_col2 = st.columns(2)

    # Graph 1: Water Requirement Breakdown
    with chart_col1:
        st.markdown("**1. Water Use Efficiency**")

        labels = ['Effective Crop Water', 'System Losses (Est.)']
        sizes = [water_vol * 0.7, water_vol * 0.3]
        colors = ['#4CAF50', '#FFC107']

        # Create opaque figure
        fig1, ax1 = plt.subplots(figsize=(4, 3))
        fig1.patch.set_facecolor('white') # Opaque background
        ax1.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90, colors=colors)
        ax1.axis('equal')
        st.pyplot(fig1)

    # Graph 2: Monthly Trend (Converted to Matplotlib for opacity)
    with chart_col2:
        st.markdown("**2. Seasonal Planning Guide**")

        months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
        avg_runtimes = [45, 50, 65, 80, 90, 60]

        # Create opaque figure
        fig2, ax2 = plt.subplots(figsize=(4, 3))
        fig2.patch.set_facecolor('white') # Opaque background
        ax2.set_facecolor('white') # Opaque plot area

        ax2.bar(months, avg_runtimes, color="#2196F3")
        ax2.set_ylabel("Avg Minutes")
        ax2.set_title("Projected Runtime", fontsize=10, fontweight='bold')
        ax2.grid(axis='y', linestyle='--', alpha=0.5)

        st.pyplot(fig2)

    # --- C. System Logic Explanation ---
    with st.expander("ℹ️ See How It Works (System Logic)"):
        st.write(f"""
        1. **Input:** The system reads `Max Temp: {temp_max}°C`, `Humidity: {humidity}%`, `Wind: {wind_speed} m/s`.
        2. **AI Inference:** The Random Forest Model (simulated) predicts an **ET0 of {predicted_et0:.2f} mm**.
        3. **Agronomy Layer:** {crop_type} has a Crop Coefficient (**Kc**) of {1.2 if crop_type=='Rice' else '...'}.
        4. **Calculation:** {predicted_et0:.2f} (ET0) × Kc × {farm_area} (ha) = **{water_vol:,.0f} Liters**.
        5. **Scheduling:** {water_vol:,.0f} L ÷ {pump_rate} L/hr = **{run_time:.0f} Minutes**.
        """)